spring:
  application:
    name: SPRING_MINI_PROJECT_001_Group1
  datasource:
    url: jdbc:postgresql://localhost:5432/spring-min-project_db
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update






















